services:
  digital-hub-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: digital-hub-web:latest
    container_name: digital-hub-web
    restart: always

    env_file:
      - .env

    networks:
      - internal
      - web

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"

      # Redirect hub.leonidk.de -> leonidk.de
      - "traefik.http.routers.hub-redirect.rule=Host(`hub.leonidk.de`)"
      - "traefik.http.routers.hub-redirect.entrypoints=websecure"
      - "traefik.http.routers.hub-redirect.tls=true"
      - "traefik.http.routers.hub-redirect.middlewares=redirect-to-root"

      - "traefik.http.middlewares.redirect-to-root.redirectregex.regex=^https?://hub\\.leonidk\\.de/(.*)"
      - "traefik.http.middlewares.redirect-to-root.redirectregex.replacement=https://leonidk.de/$1"
      - "traefik.http.middlewares.redirect-to-root.redirectregex.permanent=true"

      # HTTP
      - "traefik.http.routers.hub.rule=Host(`leonidk.de`)"
      - "traefik.http.routers.hub.entrypoints=web"
      - "traefik.http.routers.hub.service=hub"

      # HTTPS
      - "traefik.http.routers.hub-secure.rule=Host(`leonidk.de`)"
      - "traefik.http.routers.hub-secure.entrypoints=websecure"
      - "traefik.http.routers.hub-secure.tls.certresolver=le"
      - "traefik.http.routers.hub-secure.service=hub"

      # service hub → порт 3000
      - "traefik.http.services.hub.loadbalancer.server.port=3000"

  tutor-site:
    image: nginx:alpine
    container_name: tutor-site
    restart: always

    volumes:
      - /home/digital-hub/tutor-site:/usr/share/nginx/html:ro

    networks:
      - web

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"

      # HTTP
      - "traefik.http.routers.tutor.rule=Host(`tutor.leonidk.de`)"
      - "traefik.http.routers.tutor.entrypoints=web"
      - "traefik.http.routers.tutor.service=tutor"

      # HTTPS
      - "traefik.http.routers.tutor-secure.rule=Host(`tutor.leonidk.de`)"
      - "traefik.http.routers.tutor-secure.entrypoints=websecure"
      - "traefik.http.routers.tutor-secure.tls.certresolver=le"
      - "traefik.http.routers.tutor-secure.service=tutor"

      # service tutor → порт 80 (стандартный для nginx)
      - "traefik.http.services.tutor.loadbalancer.server.port=80"

networks:
  web:
    external: true
  internal:
    internal: true