services:
  digital-hub-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: digital-hub-web:latest
    container_name: digital-hub-web
    restart: always

    env_file:
      - .env

    networks:
      - internal
      - web

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"

      # HTTP
      - "traefik.http.routers.hub.rule=Host(`hub.leonidk.de`)"
      - "traefik.http.routers.hub.entrypoints=web"
      - "traefik.http.routers.hub.service=hub"

      # HTTPS
      - "traefik.http.routers.hub-secure.rule=Host(`hub.leonidk.de`)"
      - "traefik.http.routers.hub-secure.entrypoints=websecure"
      - "traefik.http.routers.hub-secure.tls.certresolver=le"
      - "traefik.http.routers.hub-secure.service=hub"

      # service hub → порт 3000
      - "traefik.http.services.hub.loadbalancer.server.port=3000"

networks:
  web:
    external: true
  internal:
    internal: true
